# Generated by Django 5.2.2 on 2025-06-09 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=7)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='IBOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=7)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.CharField(max_length=20)),
                ('quant', models.IntegerField()),
                ('estrategia', models.CharField(choices=[('61.8', '61.8'), ('Trap', 'Trap'), ('PingPong', 'PingPong'), ('S3', 'S3'), ('Max10', 'Max10'), ('Rompimento', 'Rompimento'), ('Win15', 'Win15'), ('Win30', 'Win30'), ('Win60', 'Win60')], max_length=20)),
                ('lado', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10)),
                ('preco_entrada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_saida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
