# Generated by Django 5.2.2 on 2025-06-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado')], default='FINALIZADO', max_length=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='preco_saida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
