# Generated by Django 5.2.2 on 2025-06-09 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trade_status_alter_trade_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='trade',
            name='estrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estrategia'),
        ),
    ]
